"""added queue table

Peek Plugin Database Migration Script

Revision ID: d4ffb9c5cb27
Revises: 19b2a8d326ad
Create Date: 2020-04-18 16:15:31.166637

"""

# revision identifiers, used by Alembic.
revision = 'd4ffb9c5cb27'
down_revision = '19b2a8d326ad'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventDBRawValueQueue',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('modelSetId', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('rawValue', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'modelSetId', 'key', 'rawValue'),
                    schema='pl_eventdb'
                    )

    op.add_column('EventDBModelSet', sa.Column('key', sa.String(), nullable=True),
                  schema='pl_eventdb')

    op.execute('''UPDATE "pl_eventdb"."EventDBModelSet"
                  SET "key" = "name"''')

    op.alter_column('EventDBModelSet', 'key', type_=sa.String(), nullable=False,
                    schema='pl_eventdb')
    op.create_unique_constraint('idx_eventdbModelSet_key', 'EventDBModelSet', ['key'],
                                schema='pl_eventdb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_eventdbModelSet_key', 'EventDBModelSet', schema='pl_eventdb',
                       type_='unique')
    op.drop_column('EventDBModelSet', 'key', schema='pl_eventdb')
    op.drop_table('EventDBRawValueQueue', schema='pl_eventdb')
    # ### end Alembic commands ###
